- name: Send Email with Brevo
  if: github.event_name == 'issues' && github.event.action == 'opened'
  run: |
    curl -X POST https://api.brevo.com/v3/smtp/email \
      -H "accept: application/json" \
      -H "api-key: ${{ secrets.BREVO_API_KEY }}" \
      -H "content-type: application/json" \
      -d '{
        "sender": {
          "name": "Upptime Alert",
          "email": "contact@sukuncloud.com"
        },
        "to": [{
          "email": "suresh.mahawar1988@gmail.com",
          "name": "Sukun"
        }],
        "subject": "Upptime Alert: New Downtime Issue",
        "htmlContent": "<p>A new issue has been created for a downtime event. Check: <a href=\"https://github.com/${{ github.repository }}/issues\">GitHub Issues</a></p>"
      }'
