- name: Send Email Alert
  if: github.event_name == 'issues' && github.event.action == 'opened'
  run: |
    curl --request POST \
      --url https://api.sendgrid.com/v3/mail/send \
      --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
      --header 'Content-Type: application/json' \
      --data '{
        "personalizations": [
          {
            "to": [{"email": "your-email@example.com"}],
            "subject": "Upptime Alert: New Issue Created"
          }
        ],
        "from": {"email": "alert@yourdomain.com"},
        "content": [
          {
            "type": "text/plain",
            "value": "A new downtime issue has been created by Upptime. Check GitHub for details: https://github.com/${{ github.repository }}/issues"
          }
        ]
      }'
